src/ProjectSigma/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectSigma.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }
        [Required]
        [Phone]
        public string Phone { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Message { get; set; }
    }
}

src/ProjectSigma/Controllers/Web/AppController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectSigma.Repository;
using ProjectSigma.Services;
using ProjectSigma.ViewModels;

namespace ProjectSigma.Controllers.Web
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        private readonly IMessageRepository _repository;

        public AppController(IMailService service, IMessageRepository repository)
        {
            _mailService = service;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var email = Startup.Configuration["AppSettings:SiteEmailAddress"];
                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("", "Could not send email, configuration problem");
                }
                _repository.AddMessage(model);
                if (_repository.SaveAll() && await _mailService.SendMail(model))
                {
                    ModelState.Clear();
                    ViewBag.Error = false;
                    ViewBag.Message = "Mail sent, Thanks";
                }
                else
                {
                    ViewBag.Error = true;
                    ViewBag.Message = "Sorry, there is an error pls try again later";
                }
            }

            return View();
        }
    }
}

src/ProjectSigma/Views/App/About.cshtml
@using ProjectSigma
@{
    ViewBag.Title = "About us";
}
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @Resource.Name
                <small>@Resource.About_us</small>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </div>
        <div class="col-md-6">
            <h2>About @Resource.Name</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
        </div>
    </div>
    <!-- /.row -->
    <!-- Team Members -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Team</h2>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>
                        John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>
                        John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>
                        John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- Our Customers -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Customers</h2>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
    </div>
    <!-- /.row -->
    <hr>
</div>

src/ProjectSigma/Views/App/Contact.cshtml
@using ProjectSigma
@model ProjectSigma.ViewModels.ContactViewModel
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
    <script type="text/javascript">
   $(document).ready(function () {
     initialize();
   });
   function initialize() {
       var mapOptions = {
           center: new google.maps.LatLng(@Resource.Address_Latitude, @Resource.Address_Longitude),
           zoom: 17,
           mapTypeId: google.maps.MapTypeId.ROADMAP
       };
       var map = new google.maps.Map(document.getElementById("map_canvas"),
         mapOptions);
       // create a marker
       var latlng = new google.maps.LatLng(@Resource.Address_Latitude, @Resource.Address_Longitude);
       var marker = new google.maps.Marker({
           position: latlng,
           map: map,
           title: 'Latitude: ' + latlng.Ya + ' Longitude :' + latlng.Za,
           draggable: true
       });
       infoWindow = new google.maps.InfoWindow({
           content: "Sigma Consulting RMIT <br /> @Resource.Address"
       });
       infoWindow.open(map, marker);
       geocoder = new google.maps.Geocoder();
       //Update postal address when the marker is dragged
       google.maps.event.addListener(marker, 'click', function () { //dragend
           geocoder.geocode({ latLng: marker.getPosition() }, function (responses) {
               if (responses && responses.length > 0) {
                   infoWindow.setContent(
                   "<div style=\"font-size:smaller;\">" + responses[0].formatted_address
                   );
                   infoWindow.open(map, marker);
               } else {
                   alert('Error: Google Maps could not determine the address of this location.');
               }
           });
           map.panTo(marker.getPosition());
       });
       // Close the marker window when being dragged
       google.maps.event.addListener(marker, 'dragstart', function () {
           infoWindow.close(map, marker);
       });
   }
    </script>
}
<div>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>@Resource.Contact_Us</h2>
            </div>
        </div>
        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                <!-- Embedded Google Map -->
                @*iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>*@
                <div id="map_canvas">
                </div>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p>
                    @Resource.Address<br>
                </p>
                <p>
                    <i class="fa fa-phone"></i>
                    <abbr title="Phone">P</abbr>: @Resource.About_us_phone
                </p>
                <p>
                    <i class="fa fa-envelope-o"></i>
                    <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">@Resource.About_us_email</a>
                </p>
                <p>
                    <i class="fa fa-clock-o"></i>
                    <abbr title="Hours">H</abbr>: @Resource.About_us_openning_hours
                </p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->
        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
        <div class="row">
            <div class="col-md-8">
                <h3>Send us a Message</h3>
                @if (ViewBag.Message == null)
                {
                    <form name="sentMessage" id="contactForm" method="post">
                        <div class="control-group form-group">
                            <div class="controls">
                                <label asp-for="Name">Full Name:</label>
                                <input asp-for="Name" type="text" class="form-control" id="name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label asp-for="Phone">Phone Number:</label>
                                <input type="tel" asp-for="Phone" class="form-control" id="phone">
                                <span class="text-danger" asp-validation-for="Phone"></span>
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label asp-for="Email">Email Address:</label>
                                <input type="email" asp-for="Email" class="form-control" id="email">
                                <span class="text-danger" asp-validation-for="Email"></span>
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label asp-for="Message">Message:</label>
                                <textarea asp-for="Message" rows="10" cols="100" class="form-control" id="message" maxlength="999" style="resize: none"></textarea>
                                <span class="text-danger" asp-validation-for="Message"></span>
                            </div>
                        </div>
                        <div id="success"></div>
                        <div class="form-g">
                            <button type="submit" class="btn btn-primary">Send Message</button>
                        </div>
                    </form>
                }
                else if (@ViewBag.Error)
                {
                    <div class="alert alert-danger">@ViewBag.Message</div>
                }
                else
                {
                    <div class="alert alert-success">Thank you for your message </div>
                }
            </div>
        </div>
    </div>
    <!-- /.row -->
    <hr>

    @*<div asp-validation-summary="ValidationSummary.ModelOnly"></div>*@
    @*<label asp-for="Name">Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
        <label asp-for="Email">Email</label>
        <input type="email" asp-for="Email" />
        <span asp-validation-for="Email"></span>
        <label asp-for="Message">Message</label>
        <textarea cols="40" rows="4" asp-for="Message"></textarea>
        <span asp-validation-for="Message"></span>
        <div>
            <input type="submit" value="Send Message" />
        </div>*@
</div>

src/ProjectSigma/Views/App/Index.cshtml
@using ProjectSigma
@{
    ViewBag.Title = "Home";
}

<!-- Header Carousel -->
<div id="carousel-container" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="img-responsive" src="~/img/Consulting1.jpg">
            @*<div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>*@
        </div>
        <div class="item">
            <img class="img-responsive" src="~/img/Consulting2.png">
        </div>
        <div class="item">
            <img class="img-responsive" src="~/img/Consulting3.jpg">
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-container" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-container" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- Page Content -->
<div class="container">
    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Welcome to Sigma Consulting
            </h1>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> Business feature 1 </h4>
                </div>
                <div class="panel-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                    <a href="#" class="btn btn-default">Learn More</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-gift"></i> Business feature 2</h4>
                </div>
                <div class="panel-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                    <a href="#" class="btn btn-default">Learn More</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-compass"></i> Business feature 3</h4>
                </div>
                <div class="panel-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                    <a href="#" class="btn btn-default">Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- Portfolio Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Portfolio Heading</h2>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
        <div class="col-md-4 col-sm-6">
            <a href="portfolio-item.html">
                <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
            </a>
        </div>
    </div>
    <!-- /.row -->
    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Modern Business Features</h2>
        </div>
        <div class="col-md-6">
            <p>The Modern Business template by Start Bootstrap includes:</p>
            <ul>
                <li>
                    <strong>Bootstrap v3.2.0</strong>
                </li>
                <li>jQuery v1.11.0</li>
                <li>Font Awesome v4.1.0</li>
                <li>Working PHP contact form with validation</li>
                <li>Unstyled page elements for easy customization</li>
                <li>17 HTML pages</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450" alt="">
        </div>
    </div>
    <!-- /.row -->
    <hr>
    <!-- Call to Action Section -->
    <div class="well">
        <div class="row">
            <div class="col-md-8">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
            </div>
        </div>
    </div>
    <hr>
</div>
<!-- Script to Activate the Carousel -->

src/ProjectSigma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/modern-business.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <div>
        @*<ul class="nav">
                <li><a asp-controller="App" asp-action="About">About</a></li>
                <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            </ul>*@
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" asp-controller="App" asp-action="Index">Sigma Consulting</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a asp-controller="App" asp-action="Index">Home</a>
                            </li>
                            <li>
                                <a asp-controller="App" asp-action="About">About</a>
                            </li>
                            <li>
                                <a asp-controller="App" asp-action="Contact">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
            <div id="main" class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @*<script type="text/javascript" src="~/lib/bootswatch/yeti/bootstrap.min.css"></script>*@
    @RenderSection("Scripts", false)
</body>
</html>